export const data = [
  {
    id: 1,
    first_name: "John Doe",
    last_name: "John Doe",
    email: "johndoe@example.com",
    is_verified: true,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    description: "Software engineer with a passion for music and photography.",
  },
  {
    id: 2,
    first_name: "Jane Smith",
    last_name: "Jane Smith",
    email: "janesmith@example.com",
    is_verified: false,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    description: "Freelance writer and editor with a love for coffee and cats.",
  },
  {
    id: 3,
    first_name: "Bob",
    last_name: "Johnson",
    email: "bobjohnson@example.com",
    is_verified: true,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    description:
      "Marketing professional with a passion for travel and adventure.",
  },
  {
    id: 4,
    first_name: "Emily",
    last_name: "Rodriguez",
    email: "emilyrodriguez@example.com",
    is_verified: true,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    description:
      "Graphic designer with a love for all things vintage and retro.",
  },
  {
    id: 5,
    first_name: "David",
    last_name: "Lee",
    email: "davidlee@example.com",
    is_verified: false,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    description:
      "Aspiring chef with a passion for fusion cuisine and molecular gastronomy.",
  },
  {
    id: 6,
    first_name: "Sarah",
    last_name: "Kim",
    email: "sarahkim@example.com",
    is_verified: true,
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    description:
      "Fashion blogger with a love for vintage clothing and streetwear.",
  },
  {
    id: 7,
    first_name: "Alex",
    last_name: "Wong",
    email: "alexwong@example.com",
    is_verified: false,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    description:
      "Fitness enthusiast with a passion for strength training and bodybuilding.",
  },
  {
    id: 8,
    first_name: "Karen",
    last_name: "Chen",
    email: "karenchen@example.com",
    is_verified: true,
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    description: "Yoga instructor with a love for mindfulness and meditation.",
  },
  {
    id: 9,
    first_name: "Michael",
    last_name: "Kim",
    email: "michaelkim@example.com",
    is_verified: true,
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    description:
      "Artist and illustrator with a passion for comics and graphic novels.",
  },
  {
    id: 10,
    first_name: "Jennifer",
    last_name: "Lee",
    email: "jenniferlee@example.com",
    is_verified: false,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    description: "Software engineer with a passion for music and photography.",
  },
];
